### ISSUE TITLE
Expose WML training source code explicitly in the notebook

### ISSUE THREAD

**Issue by philippe-gregoire** [IBM/watson-machine-learning-samples#16]
This is a request to simplify and enhance the examples which used an opaque zipped `.py` source to run in WML training backend.
The enhancement idea would be to extract that code from the zipss, and place it in a `%writefile` cell in the notebook, so that the code can be inspected and modified.
The code would then be zipped from the notebook and provided to WML as usual.

**Comment by JanSoltysik** [comment]
I will try to add this modification to notebooks containing deep learning experiments.

**Comment by JanSoltysik** [comment]
I gave up on your idea because some of model definitions are constructed from more than 300 lines of code. 
And pasting it to the notebook would make them significantly less readable.
Instead I added a small 2 cell section after downloading compressed model definition of following format:
 - **Tip**: Convert bellow cell to code and run it to see definition's code.
 - `uzip -oqd . <model>.zip && cat <model>.py`
