### ISSUE TITLE
Feedback on the Langraph agent template

### ISSUE THREAD

**Issue by alexgseymour** [IBM/watson-machine-learning-samples#50]
Issue to provide feedback on the Langraph agent deployment template - https://github.com/IBM/watson-machine-learning-samples/tree/master/cloud/ai-service-templates/function-calling

**Comment by alexgseymour** [comment]
- Would recommend we rename the directory to `langraph-agent` to more accurately represent what the template is focused on.
- Do we need the subdirectory `/ai_service_function_calling` within the `/src` directory. May be cleaner to have those files directly within the `/src` directory.
- Doesn't demonstrate how AI Services can support the streaming of events back

**Comment by dglozic** [comment]
I strongly recommend comparing notes with x.ai Agent Builder team. Our generated AI Service code using LangGraph supports streaming in a message format compatible with OpenAI and Chat API streaming messages for tool calling, tool results and final LLM token chunks. It would be good to be consistent here since AI Services can technically return anything and we can cause a lot of inconsistencies if not defining a recommended streaming schema.

**Comment by LukaszCmielowski** [comment]
Let's move that conversation to [IBM github.](https://github.ibm.com)
